### PR TITLE
Add DEI statement, address name pronunciation, add prodev link

### LINKED ISSUE #140: Recommend asking about name pronunciation
The final bullet point in the section [What we expect and why](https://bloom-handbook.netlify.app/sections/code-of-conduct/#what-we-expect-and-why) says:

- Treat others’ identities and cultures with respect. Make an effort to say people's names correctly and refer to them by their stated pronouns.

I'd like to suggest editing "Make an effort to say people's names correctly" to something like "If you are unsure how to pronounce someone's name, ask them how they would like their name pronounced and make an effort to say it correctly." 

Basically, don’t assume you know what “correct” pronunciation is. 

I have personal feelings about this one from several bad workplace experiences from well-intentioned colleagues who decided what correct pronunciation was for me. I am happy to share if more clarification or explanation is needed to make an edit.

### LINKED ISSUE #141: Add a DEI statement to the About Bloom section?
We currently have a diversity statement on our Jobs page, but I feel like having it in our handbook will be a good addition. 
https://docs.google.com/document/d/1MQuHagd8QqFct3JVgGuhEufNBHpwg0slqKV_YrmGyzo/edit#heading=h.wjc06bsbp482

### LINKED ISSUE #143: Expand ProDev messaging

### PR DESCRIPTION
**Pull request by dottiebobottie**
## Pull Request Background
Addresses name pronunciation in Code of Conduct, adds DEI statement to About Bloom, and pro dev link has been added 
### GitHub Issue
- Closes #141 
- Closes #140 
- Closes #143 
### What Changed
List any major changes to files and/or project functionality for this project.
- Added DEI statement to About Bloom
- Added [this list](https://docs.google.com/document/d/17qkJeBXQL3PsmHNJaGdtkzyS4sfvV4QDi2aGkGwVfCk/edit#heading=h.36bky2edfxi8) for ProDev recommendation
- Addressed name pronunciation ask in Code of Conduct

### CODE REVIEW

**Comment by ghost** [comment]
@dottiebobottie : Just checking in to see if this is ready for review or is in progress.

**Comment by coreycaitlin** [comment]
@dottiebobottie These changes look good, in general — a couple things would be good to do here before we merge:

1. Add a brief description of the changes in the PR description (above), so that we know what changed when. This is especially helpful for changing policies or noting that no policies changed, and can help tie things to open issues so we know we addressed them.
2. It would be good to make the link text for the prodev doc more descriptive, for accessibility (eg "list of professional development options" instead of "in this doc")

**Comment by dottiebobottie** [comment]
Updated this!

> @dottiebobottie These changes look good, in general — a couple things would be good to do here before we merge:
> 
> 1. Add a brief description of the changes in the PR description (above), so that we know what changed when. This is especially helpful for changing policies or noting that no policies changed, and can help tie things to open issues so we know we addressed them.
> 2. It would be good to make the link text for the prodev doc more descriptive, for accessibility (eg "list of professional development options" instead of "in this doc")

**Review by ekadernauth — DISMISSED** [review]
Reviewed and approved

**Comment by coreycaitlin** [comment]
@ekadernauth has requested to be part of the @bloom-works/handbook-finances group. In the meantime, ~if @smforelle, @emilyville or @lflockwood wants to approve, we can merge this!~ NM I'm going to merge without waiting!

**Pull request merged**
